services:
  dev:
    build: .
    volumes:
      - "$HOME/data:$HOME/data"
    tty: true
    stdin_open: true
    ports:
      - '8888:8888'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
